# Generated by Django 5.2.17 on 2026-09-15 04:18

import django.db.models.deletion
import mindease.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Therapist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("degree", models.CharField(max_length=120)),
                ("experience_years", models.PositiveIntegerField()),
                ("bio", models.TextField()),
                ("tags", mindease.fields.TagsField(default=list)),
                (
                    "session_price_inr",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("session_duration_min", models.PositiveIntegerField(default=50)),
                ("photo_url", models.URLField(blank=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "embedding",
                    mindease.fields.VectorField(blank=True, dimensions=384, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.IntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="therapists.therapist",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "start_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                        name="availability_weekday_range",
                    )
                ],
            },
        ),
    ]
