# Generated by Django 5.2.17 on 2026-09-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapist",
            name="credits",
            field=models.PositiveIntegerField(default=12),
        ),
    ]
